# Generated by Django 3.2.8 on 2021-10-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cityParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind', models.FloatField()),
                ('atmospheric_pressure', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverside.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverside.region'),
        ),
    ]
